name: Run OFAC Wallet Checker

on:
  schedule:
    - cron: '0 4 * * *'  # Run every day at 4:00 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the OFAC wallet checker script
      run: python scripts/sdn-list-pull.py

    # Commit and push updated sanctioned wallet lists
    - name: Commit and push updated OFAC sanctioned wallet lists
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add OFAC_Sanctioned_Wallet_Lists/
        git commit -m "Update OFAC_Sanctioned_Wallet_Lists with the latest results"
        git push
